apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: serving-runtime-ingress-mesh
spec:
  podSelector:
    matchLabels:
      platform.ai-ml/network-role: serving-runtime
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
      podSelector:
        matchLabels:
          app: istio-ingressgateway
          istio: ingressgateway
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: knative-serving
      podSelector:
        matchLabels:
          app: activator
