apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rbac-mlflow-tag-sync.yaml
- networkpolicy-kube-api-egress.yaml
configMapGenerator:
- name: mlflow-tag-sync-scripts
  files:
  - ../../../infra/argo-workflows/scripts/resolve_alias_and_intent.py
  - ../../../infra/argo-workflows/scripts/render_inferenceservice.py
  - ../../../infra/argo-workflows/scripts/update_mlflow_status.py
  - ../../../infra/argo-workflows/scripts/git_writeback.sh
  - ../../../infra/argo-workflows/scripts/git_prune_manifests.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "20"
