apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- tenant-credentials.yaml
- tenant-bootstrap-configmap.yaml
- tenant-bootstrap-job.yaml
- pv.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
