apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-credentials
  namespace: minio
type: Opaque
stringData:
  MLFLOW_TEAM_A_ACCESS_KEY: MLFLOWTEAMA
  MLFLOW_TEAM_A_SECRET_KEY: mlflow-teama-secret-2026
  MLFLOW_TEAM_B_ACCESS_KEY: MLFLOWTEAMB
  MLFLOW_TEAM_B_SECRET_KEY: mlflow-teamb-secret-2026
