apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: ml-team-b
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: mlflow-ml-team-b-pv
