apiVersion: v1
kind: Secret
metadata:
  name: mlflow-sync-git-credentials
  namespace: ml-team-a
type: Opaque
stringData:
  GIT_REPO_URL: http://gitea-http.gitea.svc.cluster.local:3000/gitops-admin/ai-ml.git
  GIT_DEFAULT_BRANCH: auto
  GIT_USERNAME: gitops-admin
  GIT_PASSWORD: gitops123
  GIT_AUTHOR_NAME: mlflow-sync-bot
  GIT_AUTHOR_EMAIL: mlflow-sync-bot@ai-ml.local
