apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored-by-target-selector
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        platform.mlops-on-desktop/mesh-rollout: "enabled"
