apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/knative/serving/releases/download/knative-v1.20.3/serving-core.yaml
patches:
- path: config-domain-patch.yaml
  target:
    kind: ConfigMap
    name: config-domain
    namespace: knative-serving
- path: config-deployment-patch.yaml
  target:
    kind: ConfigMap
    name: config-deployment
    namespace: knative-serving
- path: namespace-istio-injection-patch.yaml
  target:
    kind: Namespace
    name: knative-serving
- path: deployment-istio-injection-patch.yaml
  target:
    kind: Deployment
    namespace: knative-serving
