apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  namespaceSelector:
    matchNames:
    - argocd
  selector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - argocd-metrics
      - argocd-server-metrics
      - argocd-repo-server
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
