apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-workflows
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  namespaceSelector:
    matchNames:
    - argo
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow-controller-metrics
  endpoints:
  - port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    interval: 30s
    scrapeTimeout: 10s
