apiVersion: v1
kind: Namespace
metadata:
  name: ml-team-a
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: ai-ml
    platform.ai-ml/layer: teams
    platform.ai-ml/tenant: ml-team-a
    platform.ai-ml/environment: kind
