apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.failurePolicy
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.24.2
    helm:
      values: |
        autoscaleEnabled: false
        replicaCount: 1
        meshConfig:
          trustDomain: cluster.local
        global:
          caAddress: cert-manager-istio-csr.istio-system.svc:443
        env:
          ENABLE_CA_SERVER: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
