apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application-ca.yaml
- application-base.yaml
- application-cert-manager-istio-csr.yaml
- application-istiod.yaml
- application-ingressgateway.yaml
- application-mesh-security.yaml
