apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-ml-team-b-pv
  labels:
    app.kubernetes.io/name: mlflow
    platform.ai-ml/tenant: ml-team-b
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/minio-data/mlflow/ml-team-b
    type: DirectoryOrCreate
