apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving-core
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.rules
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.rules
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitops-admin/ai-ml.git
    targetRevision: HEAD
    path: infra/knative/manifests/serving-core
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
