apiVersion: v1
kind: Secret
metadata:
  name: mlflow-s3-credentials
  namespace: ml-team-a
  annotations:
    serving.kserve.io/s3-endpoint: minio.minio.svc.cluster.local:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-verifyssl: "0"
    serving.kserve.io/s3-region: us-east-1
type: Opaque
stringData:
  MINIO_ACCESS_KEY: MLFLOWTEAMA
  MINIO_SECRET_KEY: mlflow-teama-secret-2026
  AWS_ACCESS_KEY_ID: MLFLOWTEAMA
  AWS_SECRET_ACCESS_KEY: mlflow-teama-secret-2026
  AWS_DEFAULT_REGION: us-east-1
  MLFLOW_S3_ENDPOINT_URL: http://minio.minio.svc.cluster.local:9000
  MLFLOW_S3_BUCKET: mlflow-ml-team-a
  MLFLOW_TRACKING_URI: http://mlflow.ml-team-a.svc.cluster.local
